argon2-cffi==20.1.0
attrs==20.2.0
backcall==0.2.0
bleach==3.1.5
branca @ file:///home/conda/feedstock_root/build_artifacts/branca_1588860304135/work
brotlipy==0.7.0
certifi==2020.6.20
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1595805769248/work
chardet==3.0.4
click==7.1.2
cryptography @ file:///tmp/build/80754af9/cryptography_1598892038851/work
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
docutils==0.16
ediblepickle==1.1.3
entrypoints==0.3
folium @ file:///home/conda/feedstock_root/build_artifacts/folium_1588861378954/work
future==0.18.2
geocoder==1.38.1
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
ipykernel==5.3.4
ipython @ file:///tmp/build/80754af9/ipython_1598883821407/work
ipython-genutils==0.2.0
jedi @ file:///tmp/build/80754af9/jedi_1598371611696/work
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1594826976318/work
jupyter-core==4.6.3
jupyterlab==2.2.6
jupyterlab-server==1.2.0
Kivy @ file:///home/conda/feedstock_root/build_artifacts/kivy_1590522812002/work
kiwisolver==1.2.0
MarkupSafe==1.1.1
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1597876319132/work
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.1.4
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1596233721170/work
olefile==0.46
packaging==20.4
pandas @ file:///tmp/build/80754af9/pandas_1598371468004/work
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///tmp/build/80754af9/pillow_1594307295532/work
prometheus-client==0.8.0
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1598885458782/work
ptyprocess==0.6.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments==2.6.1
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pyrsistent==0.17.0
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.1
ratelim==0.1.6
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
Send2Trash==1.5.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
urllib3 @ file:///tmp/build/80754af9/urllib3_1597086586889/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
